### ISSUE TITLE
Weird segfaults on benchmark instance

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom#126]
The current CVRP clustering heuristic in `master` raises a segfault on some CVRPLIB instances (e.g. `A-n32-k5`) under very specific circumstances. From what I gathered so far, it only happens when:

- the clustering initialization scheme is set to `INIT_T::HIGHER_AMOUNT`
- the code is compiled using `-O0` with `gcc` (no problem when using `-O1`, `-O2` or `-O3`) or using `-O0` or `-O1` with `clang` (no problem when using `-O2` or `-O3`).

A backtrace seems to indicate there is something wrong when trying to retrieve the best candidate for initialization [here](https://github.com/VROOM-Project/vroom/blob/master/src/problems/cvrp/heuristics/clustering.cpp#L467-L469). The different behaviours regarding the optimization levels are quite puzzling though.

```
Thread 2 "vroom" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff3971700 (LWP 7795)]
0x00000000004335dc in std::vector<unsigned int, std::allocator<unsigned int> >::operator[](unsigned long) ()
(gdb) bt
#0  0x00000000004335dc in std::vector<unsigned int, std::allocator<unsigned int> >::operator[](unsigned long) ()
#1  0x0000000000453a4a in _ZZZN10clustering21sequential_clusteringEvENKUlT_E_clImEEDaS0_ENKUlttE_clEtt ()
#2  0x0000000000453b71 in _ZN9__gnu_cxx5__ops15_Iter_comp_iterIZZN10clustering21sequential_clusteringEvENKUlT_E_clImEEDaS3_EUlttE_EclINS_17__normal_iteratorIPKtSt6vectorItSaItEEEESF_EEbS3_T0_ ()
#3  0x0000000000453bf2 in _ZSt13__max_elementIN9__gnu_cxx17__normal_iteratorIPKtSt6vectorItSaItEEEENS0_5__ops15_Iter_comp_iterIZZN10clustering21sequential_clusteringEvENKUlT_E_clImEEDaSB_EUlttE_EEESB_SB_SB_T0_ ()
#4  0x0000000000453c72 in _ZSt11max_elementIN9__gnu_cxx17__normal_iteratorIPKtSt6vectorItSaItEEEEZZN10clustering21sequential_clusteringEvENKUlT_E_clImEEDaS9_EUlttE_ES9_S9_S9_T0_ ()
#5  0x000000000045499c in clustering::sequential_clustering() ()
#6  0x00000000004512cb in clustering::clustering(input const&, CLUSTERING_T, INIT_T, double) ()
#7  0x000000000043f393 in cvrp::solve[abi:cxx11](unsigned int) const::{lambda(std::vector<unsigned long, std::allocator<unsigned long> > const&)#1}::operator()(std::vector<unsigned long, std::allocator<unsigned long> > const&) const ()
#8  0x0000000000445467 in void std::_Bind_simple<cvrp::solve(unsigned int) const::{lambda(std::vector<unsigned long, std::allocator<unsigned long> > const&)#1} (std::vector<unsigned long, std::allocator<unsigned long> >)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) ()
#9  0x0000000000445180 in std::_Bind_simple<cvrp::solve(unsigned int) const::{lambda(std::vector<unsigned long, std::allocator<unsigned long> > const&)#1} (std::vector<unsigned long, std::allocator<unsigned long> >)>::operator()() ()
#10 0x0000000000445004 in std::thread::_Impl<std::_Bind_simple<cvrp::solve(unsigned int) const::{lambda(std::vector<unsigned long, std::allocator<unsigned long> > const&)#1} (std::vector<unsigned long, std::allocator<unsigned long> >)> >::_M_run() ()
#11 0x00007ffff6eecc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007ffff73e36ba in start_thread (arg=0x7ffff3971700) at pthread_create.c:333
#13 0x00007ffff695b41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by jcoupey** [comment]
Solved in #127.
